-- =============================================================================
-- READ-ONLY production baseline verification for Prisma migrations 0001–0008
-- =============================================================================
-- AUTO-GENERATED by scripts/generate-verify-migrations-sql.js — do not edit by hand.
-- Regenerate after changing migrations 0001–0008:
--   node scripts/generate-verify-migrations-sql.js
--
-- Usage (direct Postgres URL only — not the pooler):
--   psql "$DIRECT_URL" -f scripts/sql/verify-migrations-0001-0008.sql
--
-- This script performs SELECT-only checks. It does NOT modify the database.
-- Run BEFORE any `prisma migrate resolve --applied` commands.
-- =============================================================================

WITH
m1_enums AS (
  SELECT *
  FROM (VALUES
    ('0001_baseline', 'enum', 'StoryStatus'),
    ('0001_baseline', 'enum', 'MediaType'),
    ('0001_baseline', 'enum', 'InviteMethod'),
    ('0001_baseline', 'enum', 'DiscoveriesVisibility'),
    ('0001_baseline', 'enum', 'ConversationOrigin'),
    ('0001_baseline', 'enum', 'IntroductionVisibilityMode'),
    ('0001_baseline', 'enum', 'NotificationDigestFrequency'),
    ('0001_baseline', 'enum', 'ReportStatus'),
    ('0001_baseline', 'enum', 'ReportTargetType'),
    ('0001_baseline', 'enum', 'VerificationLevel'),
    ('0001_baseline', 'enum', 'BackgroundJobStatus'),
    ('0001_baseline', 'enum', 'TrustRankTier'),
    ('0001_baseline', 'enum', 'TrustRiskLevel'),
    ('0001_baseline', 'enum', 'SecurityEventSeverity'),
    ('0001_baseline', 'enum', 'JobPriority')
  ) AS v(migration, kind, name)
),

m1_tables AS (
  SELECT *
  FROM (VALUES
    ('0001_baseline', 'table', 'users'),
    ('0001_baseline', 'table', 'stories'),
    ('0001_baseline', 'table', 'story_tags'),
    ('0001_baseline', 'table', 'invitations'),
    ('0001_baseline', 'table', 'messages'),
    ('0001_baseline', 'table', 'posts'),
    ('0001_baseline', 'table', 'user_consents'),
    ('0001_baseline', 'table', 'admin_settings')
  ) AS v(migration, kind, name)
),

m1_columns AS (
  SELECT *
  FROM (VALUES
    ('0001_baseline', 'users', 'id'),
    ('0001_baseline', 'users', 'name'),
    ('0001_baseline', 'users', 'email'),
    ('0001_baseline', 'users', 'profile_picture'),
    ('0001_baseline', 'users', 'invites_sent'),
    ('0001_baseline', 'users', 'invites_registered'),
    ('0001_baseline', 'users', 'last_introductions_seen_at'),
    ('0001_baseline', 'users', 'phone_verified'),
    ('0001_baseline', 'users', 'email_verified'),
    ('0001_baseline', 'users', 'identity_verified'),
    ('0001_baseline', 'users', 'verification_level'),
    ('0001_baseline', 'users', 'verified_at'),
    ('0001_baseline', 'users', 'trusted_user'),
    ('0001_baseline', 'users', 'phone'),
    ('0001_baseline', 'users', 'suspended_at'),
    ('0001_baseline', 'users', 'banned_at'),
    ('0001_baseline', 'users', 'trust_risk_score'),
    ('0001_baseline', 'users', 'trust_risk_level'),
    ('0001_baseline', 'users', 'trust_risk_reviewed_at'),
    ('0001_baseline', 'users', 'trust_risk_false_positive'),
    ('0001_baseline', 'users', 'created_at'),
    ('0001_baseline', 'stories', 'id'),
    ('0001_baseline', 'stories', 'user_id'),
    ('0001_baseline', 'stories', 'media_url'),
    ('0001_baseline', 'stories', 'media_type'),
    ('0001_baseline', 'stories', 'voice_note_url'),
    ('0001_baseline', 'stories', 'text'),
    ('0001_baseline', 'stories', 'status'),
    ('0001_baseline', 'stories', 'created_at'),
    ('0001_baseline', 'stories', 'expires_at'),
    ('0001_baseline', 'stories', 'published_at'),
    ('0001_baseline', 'stories', 'introduction_category_id'),
    ('0001_baseline', 'stories', 'visibility_mode'),
    ('0001_baseline', 'story_tags', 'id'),
    ('0001_baseline', 'story_tags', 'story_id'),
    ('0001_baseline', 'story_tags', 'tagged_user_id'),
    ('0001_baseline', 'story_tags', 'tagged_external_email'),
    ('0001_baseline', 'story_tags', 'tagged_external_phone'),
    ('0001_baseline', 'story_tags', 'invitation_id'),
    ('0001_baseline', 'story_tags', 'created_at'),
    ('0001_baseline', 'invitations', 'id'),
    ('0001_baseline', 'invitations', 'email'),
    ('0001_baseline', 'invitations', 'phone_number'),
    ('0001_baseline', 'invitations', 'invite_method'),
    ('0001_baseline', 'invitations', 'invited_by'),
    ('0001_baseline', 'invitations', 'invite_token'),
    ('0001_baseline', 'invitations', 'registered'),
    ('0001_baseline', 'invitations', 'registered_user_id'),
    ('0001_baseline', 'invitations', 'created_at'),
    ('0001_baseline', 'invitations', 'expires_at'),
    ('0001_baseline', 'invitations', 'invitation_opened_at'),
    ('0001_baseline', 'invitations', 'accepted_at'),
    ('0001_baseline', 'messages', 'id'),
    ('0001_baseline', 'messages', 'sender_id'),
    ('0001_baseline', 'messages', 'receiver_id'),
    ('0001_baseline', 'messages', 'story_reference'),
    ('0001_baseline', 'messages', 'discoveries_post_reference'),
    ('0001_baseline', 'messages', 'conversation_origin'),
    ('0001_baseline', 'messages', 'message'),
    ('0001_baseline', 'messages', 'created_at'),
    ('0001_baseline', 'messages', 'read_at'),
    ('0001_baseline', 'posts', 'id'),
    ('0001_baseline', 'posts', 'user_id'),
    ('0001_baseline', 'posts', 'content'),
    ('0001_baseline', 'posts', 'media'),
    ('0001_baseline', 'posts', 'created_at'),
    ('0001_baseline', 'posts', 'expires_at'),
    ('0001_baseline', 'user_consents', 'id'),
    ('0001_baseline', 'user_consents', 'user_id'),
    ('0001_baseline', 'user_consents', 'privacy_version'),
    ('0001_baseline', 'user_consents', 'terms_version'),
    ('0001_baseline', 'user_consents', 'cookie_version'),
    ('0001_baseline', 'user_consents', 'accepted_at'),
    ('0001_baseline', 'user_consents', 'ip_address'),
    ('0001_baseline', 'user_consents', 'country'),
    ('0001_baseline', 'admin_settings', 'id'),
    ('0001_baseline', 'admin_settings', 'invite_gate_enabled'),
    ('0001_baseline', 'admin_settings', 'required_invites'),
    ('0001_baseline', 'admin_settings', 'story_expiry_hours'),
    ('0001_baseline', 'admin_settings', 'post_expiry_hours'),
    ('0001_baseline', 'admin_settings', 'discoveries_enabled'),
    ('0001_baseline', 'admin_settings', 'discoveries_expiry_hours'),
    ('0001_baseline', 'admin_settings', 'discoveries_public_enabled'),
    ('0001_baseline', 'admin_settings', 'introductions_never_expire'),
    ('0001_baseline', 'admin_settings', 'discoveries_network_depth'),
    ('0001_baseline', 'admin_settings', 'show_connection_reasons'),
    ('0001_baseline', 'admin_settings', 'enable_introduction_graph'),
    ('0001_baseline', 'admin_settings', 'allow_first_degree_discovery'),
    ('0001_baseline', 'admin_settings', 'allow_second_degree_discovery'),
    ('0001_baseline', 'admin_settings', 'allow_third_degree_discovery'),
    ('0001_baseline', 'admin_settings', 'allow_fourth_degree_discovery'),
    ('0001_baseline', 'admin_settings', 'max_discovery_depth'),
    ('0001_baseline', 'admin_settings', 'show_connection_paths'),
    ('0001_baseline', 'admin_settings', 'enable_trust_scores'),
    ('0001_baseline', 'admin_settings', 'enable_verification_layer'),
    ('0001_baseline', 'admin_settings', 'enable_introduction_categories'),
    ('0001_baseline', 'admin_settings', 'allow_user_created_categories'),
    ('0001_baseline', 'admin_settings', 'allow_category_editing'),
    ('0001_baseline', 'admin_settings', 'require_phone_verification'),
    ('0001_baseline', 'admin_settings', 'require_identity_verification'),
    ('0001_baseline', 'admin_settings', 'show_trust_scores'),
    ('0001_baseline', 'admin_settings', 'show_shared_introducers'),
    ('0001_baseline', 'admin_settings', 'enable_shared_introducer_trust'),
    ('0001_baseline', 'admin_settings', 'show_shared_introducer_counts'),
    ('0001_baseline', 'admin_settings', 'shared_introducer_weight'),
    ('0001_baseline', 'admin_settings', 'minimum_shared_introducers_for_messaging'),
    ('0001_baseline', 'admin_settings', 'minimum_shared_introducers_for_discovery'),
    ('0001_baseline', 'admin_settings', 'enable_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_in_app_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_push_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_email_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_introduction_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_discovery_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_message_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_trust_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_verification_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_announcement_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_introduction_view_notifications'),
    ('0001_baseline', 'admin_settings', 'enable_notification_digests'),
    ('0001_baseline', 'admin_settings', 'notification_digest_frequency'),
    ('0001_baseline', 'admin_settings', 'enable_discovery_controls'),
    ('0001_baseline', 'admin_settings', 'enable_granular_verification_gates'),
    ('0001_baseline', 'admin_settings', 'enable_background_jobs'),
    ('0001_baseline', 'admin_settings', 'enable_trust_rankings'),
    ('0001_baseline', 'admin_settings', 'enable_trust_recommendations'),
    ('0001_baseline', 'admin_settings', 'allow_cross_category_discovery'),
    ('0001_baseline', 'admin_settings', 'allow_discovery_messaging'),
    ('0001_baseline', 'admin_settings', 'require_shared_introducer_for_discovery'),
    ('0001_baseline', 'admin_settings', 'require_shared_introducer_for_messaging'),
    ('0001_baseline', 'admin_settings', 'hide_discovery_from_unverified_users'),
    ('0001_baseline', 'admin_settings', 'require_email_verification'),
    ('0001_baseline', 'admin_settings', 'messaging_require_phone'),
    ('0001_baseline', 'admin_settings', 'messaging_require_email'),
    ('0001_baseline', 'admin_settings', 'messaging_require_identity'),
    ('0001_baseline', 'admin_settings', 'discoveries_require_phone'),
    ('0001_baseline', 'admin_settings', 'discoveries_require_email'),
    ('0001_baseline', 'admin_settings', 'discoveries_require_identity'),
    ('0001_baseline', 'admin_settings', 'introductions_require_phone'),
    ('0001_baseline', 'admin_settings', 'introductions_require_email'),
    ('0001_baseline', 'admin_settings', 'introductions_require_identity'),
    ('0001_baseline', 'admin_settings', 'enable_specific_people_visibility'),
    ('0001_baseline', 'admin_settings', 'enable_mutual_introduction_network_visibility'),
    ('0001_baseline', 'admin_settings', 'enable_everyone_introduced_visibility'),
    ('0001_baseline', 'admin_settings', 'default_story_visibility_mode'),
    ('0001_baseline', 'admin_settings', 'allow_user_visibility_selection'),
    ('0001_baseline', 'admin_settings', 'enable_discoveries_hero_banner'),
    ('0001_baseline', 'admin_settings', 'enable_discovery_expiry_indicators'),
    ('0001_baseline', 'admin_settings', 'enable_discovery_trust_context'),
    ('0001_baseline', 'admin_settings', 'updated_at')
  ) AS v(migration, table_name, column_name)
),

m1_indexes AS (
  SELECT *
  FROM (VALUES
    ('0001_baseline', 'users_email_key'),
    ('0001_baseline', 'users_email_idx'),
    ('0001_baseline', 'users_phone_idx'),
    ('0001_baseline', 'users_verification_level_idx'),
    ('0001_baseline', 'users_trusted_user_idx'),
    ('0001_baseline', 'stories_user_id_idx'),
    ('0001_baseline', 'stories_status_idx'),
    ('0001_baseline', 'stories_expires_at_idx'),
    ('0001_baseline', 'stories_introduction_category_id_idx'),
    ('0001_baseline', 'story_tags_invitation_id_key'),
    ('0001_baseline', 'story_tags_story_id_idx'),
    ('0001_baseline', 'story_tags_tagged_user_id_idx'),
    ('0001_baseline', 'story_tags_tagged_external_email_idx'),
    ('0001_baseline', 'story_tags_tagged_external_phone_idx'),
    ('0001_baseline', 'story_tags_story_id_tagged_user_id_key'),
    ('0001_baseline', 'story_tags_story_id_tagged_external_email_key'),
    ('0001_baseline', 'story_tags_story_id_tagged_external_phone_key'),
    ('0001_baseline', 'invitations_invite_token_key'),
    ('0001_baseline', 'invitations_email_idx'),
    ('0001_baseline', 'invitations_phone_number_idx'),
    ('0001_baseline', 'invitations_invited_by_idx'),
    ('0001_baseline', 'invitations_invite_token_idx'),
    ('0001_baseline', 'messages_sender_id_receiver_id_created_at_idx'),
    ('0001_baseline', 'messages_receiver_id_sender_id_created_at_idx'),
    ('0001_baseline', 'messages_story_reference_idx'),
    ('0001_baseline', 'messages_discoveries_post_reference_idx'),
    ('0001_baseline', 'posts_user_id_idx'),
    ('0001_baseline', 'posts_expires_at_idx'),
    ('0001_baseline', 'user_consents_user_id_idx')
  ) AS v(migration, index_name)
),

m1_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0001_baseline', 'stories_user_id_fkey'),
    ('0001_baseline', 'story_tags_story_id_fkey'),
    ('0001_baseline', 'story_tags_tagged_user_id_fkey'),
    ('0001_baseline', 'story_tags_invitation_id_fkey'),
    ('0001_baseline', 'invitations_invited_by_fkey'),
    ('0001_baseline', 'messages_sender_id_fkey'),
    ('0001_baseline', 'messages_receiver_id_fkey'),
    ('0001_baseline', 'messages_story_reference_fkey'),
    ('0001_baseline', 'posts_user_id_fkey'),
    ('0001_baseline', 'user_consents_user_id_fkey')
  ) AS v(migration, constraint_name)
),

m2_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m2_tables AS (
  SELECT *
  FROM (VALUES
    ('0002_discoveries', 'table', 'conversation_contexts'),
    ('0002_discoveries', 'table', 'discoveries_posts'),
    ('0002_discoveries', 'table', 'discoveries_likes'),
    ('0002_discoveries', 'table', 'discoveries_comments'),
    ('0002_discoveries', 'table', 'discoveries_bookmarks'),
    ('0002_discoveries', 'table', 'discoveries_shares')
  ) AS v(migration, kind, name)
),

m2_columns AS (
  SELECT *
  FROM (VALUES
    ('0002_discoveries', 'conversation_contexts', 'id'),
    ('0002_discoveries', 'conversation_contexts', 'user_a_id'),
    ('0002_discoveries', 'conversation_contexts', 'user_b_id'),
    ('0002_discoveries', 'conversation_contexts', 'origin'),
    ('0002_discoveries', 'conversation_contexts', 'story_reference'),
    ('0002_discoveries', 'conversation_contexts', 'discoveries_post_reference'),
    ('0002_discoveries', 'conversation_contexts', 'created_at'),
    ('0002_discoveries', 'discoveries_posts', 'id'),
    ('0002_discoveries', 'discoveries_posts', 'user_id'),
    ('0002_discoveries', 'discoveries_posts', 'content'),
    ('0002_discoveries', 'discoveries_posts', 'media_url'),
    ('0002_discoveries', 'discoveries_posts', 'media_type'),
    ('0002_discoveries', 'discoveries_posts', 'visibility'),
    ('0002_discoveries', 'discoveries_posts', 'introduction_category_id'),
    ('0002_discoveries', 'discoveries_posts', 'visibility_mode'),
    ('0002_discoveries', 'discoveries_posts', 'created_at'),
    ('0002_discoveries', 'discoveries_posts', 'expires_at'),
    ('0002_discoveries', 'discoveries_likes', 'id'),
    ('0002_discoveries', 'discoveries_likes', 'post_id'),
    ('0002_discoveries', 'discoveries_likes', 'user_id'),
    ('0002_discoveries', 'discoveries_likes', 'created_at'),
    ('0002_discoveries', 'discoveries_comments', 'id'),
    ('0002_discoveries', 'discoveries_comments', 'post_id'),
    ('0002_discoveries', 'discoveries_comments', 'user_id'),
    ('0002_discoveries', 'discoveries_comments', 'content'),
    ('0002_discoveries', 'discoveries_comments', 'created_at'),
    ('0002_discoveries', 'discoveries_bookmarks', 'id'),
    ('0002_discoveries', 'discoveries_bookmarks', 'post_id'),
    ('0002_discoveries', 'discoveries_bookmarks', 'user_id'),
    ('0002_discoveries', 'discoveries_bookmarks', 'created_at'),
    ('0002_discoveries', 'discoveries_shares', 'id'),
    ('0002_discoveries', 'discoveries_shares', 'post_id'),
    ('0002_discoveries', 'discoveries_shares', 'user_id'),
    ('0002_discoveries', 'discoveries_shares', 'created_at')
  ) AS v(migration, table_name, column_name)
),

m2_indexes AS (
  SELECT *
  FROM (VALUES
    ('0002_discoveries', 'conversation_contexts_user_a_id_idx'),
    ('0002_discoveries', 'conversation_contexts_user_b_id_idx'),
    ('0002_discoveries', 'conversation_contexts_user_a_id_user_b_id_key'),
    ('0002_discoveries', 'discoveries_posts_user_id_idx'),
    ('0002_discoveries', 'discoveries_posts_visibility_created_at_idx'),
    ('0002_discoveries', 'discoveries_posts_expires_at_idx'),
    ('0002_discoveries', 'discoveries_likes_post_id_user_id_key'),
    ('0002_discoveries', 'discoveries_comments_post_id_created_at_idx'),
    ('0002_discoveries', 'discoveries_bookmarks_post_id_user_id_key'),
    ('0002_discoveries', 'discoveries_shares_post_id_idx')
  ) AS v(migration, index_name)
),

m2_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0002_discoveries', 'messages_discoveries_post_reference_fkey'),
    ('0002_discoveries', 'conversation_contexts_user_a_id_fkey'),
    ('0002_discoveries', 'conversation_contexts_user_b_id_fkey'),
    ('0002_discoveries', 'conversation_contexts_story_reference_fkey'),
    ('0002_discoveries', 'conversation_contexts_discoveries_post_reference_fkey'),
    ('0002_discoveries', 'discoveries_posts_user_id_fkey'),
    ('0002_discoveries', 'discoveries_likes_post_id_fkey'),
    ('0002_discoveries', 'discoveries_likes_user_id_fkey'),
    ('0002_discoveries', 'discoveries_comments_post_id_fkey'),
    ('0002_discoveries', 'discoveries_comments_user_id_fkey'),
    ('0002_discoveries', 'discoveries_bookmarks_post_id_fkey'),
    ('0002_discoveries', 'discoveries_bookmarks_user_id_fkey'),
    ('0002_discoveries', 'discoveries_shares_post_id_fkey'),
    ('0002_discoveries', 'discoveries_shares_user_id_fkey')
  ) AS v(migration, constraint_name)
),

m3_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m3_tables AS (
  SELECT *
  FROM (VALUES
    ('0003_trust_graph', 'table', 'user_connections'),
    ('0003_trust_graph', 'table', 'introduction_categories'),
    ('0003_trust_graph', 'table', 'shared_introducer_relationships')
  ) AS v(migration, kind, name)
),

m3_columns AS (
  SELECT *
  FROM (VALUES
    ('0003_trust_graph', 'user_connections', 'id'),
    ('0003_trust_graph', 'user_connections', 'source_user_id'),
    ('0003_trust_graph', 'user_connections', 'target_user_id'),
    ('0003_trust_graph', 'user_connections', 'degree'),
    ('0003_trust_graph', 'user_connections', 'introduced_via_story_id'),
    ('0003_trust_graph', 'user_connections', 'shared_introducer_count'),
    ('0003_trust_graph', 'user_connections', 'trust_score'),
    ('0003_trust_graph', 'user_connections', 'trust_rank'),
    ('0003_trust_graph', 'user_connections', 'trust_rank_tier'),
    ('0003_trust_graph', 'user_connections', 'highest_trust_path'),
    ('0003_trust_graph', 'user_connections', 'created_at'),
    ('0003_trust_graph', 'user_connections', 'updated_at'),
    ('0003_trust_graph', 'introduction_categories', 'id'),
    ('0003_trust_graph', 'introduction_categories', 'name'),
    ('0003_trust_graph', 'introduction_categories', 'description'),
    ('0003_trust_graph', 'introduction_categories', 'icon'),
    ('0003_trust_graph', 'introduction_categories', 'color'),
    ('0003_trust_graph', 'introduction_categories', 'is_system'),
    ('0003_trust_graph', 'introduction_categories', 'is_active'),
    ('0003_trust_graph', 'introduction_categories', 'created_by_user_id'),
    ('0003_trust_graph', 'introduction_categories', 'created_at'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'user_a_id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'user_b_id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'shared_introducer_id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'first_introduction_story_id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'second_introduction_story_id'),
    ('0003_trust_graph', 'shared_introducer_relationships', 'created_at')
  ) AS v(migration, table_name, column_name)
),

m3_indexes AS (
  SELECT *
  FROM (VALUES
    ('0003_trust_graph', 'user_connections_source_user_id_idx'),
    ('0003_trust_graph', 'user_connections_target_user_id_idx'),
    ('0003_trust_graph', 'user_connections_degree_idx'),
    ('0003_trust_graph', 'user_connections_source_user_id_degree_idx'),
    ('0003_trust_graph', 'user_connections_source_user_id_shared_introducer_count_idx'),
    ('0003_trust_graph', 'user_connections_source_user_id_trust_score_idx'),
    ('0003_trust_graph', 'user_connections_source_user_id_target_user_id_key'),
    ('0003_trust_graph', 'introduction_categories_is_active_idx'),
    ('0003_trust_graph', 'introduction_categories_name_key'),
    ('0003_trust_graph', 'shared_introducer_relationships_user_a_id_user_b_id_idx'),
    ('0003_trust_graph', 'shared_introducer_relationships_shared_introducer_id_idx'),
    ('0003_trust_graph', 'shared_introducer_relationships_user_a_id_user_b_id_shared__key')
  ) AS v(migration, index_name)
),

m3_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0003_trust_graph', 'stories_introduction_category_id_fkey'),
    ('0003_trust_graph', 'discoveries_posts_introduction_category_id_fkey'),
    ('0003_trust_graph', 'user_connections_source_user_id_fkey'),
    ('0003_trust_graph', 'user_connections_target_user_id_fkey'),
    ('0003_trust_graph', 'user_connections_introduced_via_story_id_fkey'),
    ('0003_trust_graph', 'introduction_categories_created_by_user_id_fkey'),
    ('0003_trust_graph', 'shared_introducer_relationships_user_a_id_fkey'),
    ('0003_trust_graph', 'shared_introducer_relationships_user_b_id_fkey'),
    ('0003_trust_graph', 'shared_introducer_relationships_shared_introducer_id_fkey'),
    ('0003_trust_graph', 'shared_introducer_relationships_first_introduction_story_i_fkey'),
    ('0003_trust_graph', 'shared_introducer_relationships_second_introduction_story__fkey')
  ) AS v(migration, constraint_name)
),

m4_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m4_tables AS (
  SELECT *
  FROM (VALUES
    ('0004_notifications', 'table', 'notifications'),
    ('0004_notifications', 'table', 'notification_preferences'),
    ('0004_notifications', 'table', 'push_subscriptions'),
    ('0004_notifications', 'table', 'analytics_events')
  ) AS v(migration, kind, name)
),

m4_columns AS (
  SELECT *
  FROM (VALUES
    ('0004_notifications', 'notifications', 'id'),
    ('0004_notifications', 'notifications', 'user_id'),
    ('0004_notifications', 'notifications', 'actor_id'),
    ('0004_notifications', 'notifications', 'type'),
    ('0004_notifications', 'notifications', 'title'),
    ('0004_notifications', 'notifications', 'message'),
    ('0004_notifications', 'notifications', 'entity_type'),
    ('0004_notifications', 'notifications', 'entity_id'),
    ('0004_notifications', 'notifications', 'is_read'),
    ('0004_notifications', 'notifications', 'read_at'),
    ('0004_notifications', 'notifications', 'created_at'),
    ('0004_notifications', 'notification_preferences', 'id'),
    ('0004_notifications', 'notification_preferences', 'user_id'),
    ('0004_notifications', 'notification_preferences', 'enable_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_introduction_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_invitation_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_discovery_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_message_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_trust_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_verification_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_email_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_push_notifications'),
    ('0004_notifications', 'notification_preferences', 'enable_in_app_notifications'),
    ('0004_notifications', 'notification_preferences', 'quiet_hours_enabled'),
    ('0004_notifications', 'notification_preferences', 'quiet_hours_start'),
    ('0004_notifications', 'notification_preferences', 'quiet_hours_end'),
    ('0004_notifications', 'notification_preferences', 'created_at'),
    ('0004_notifications', 'notification_preferences', 'updated_at'),
    ('0004_notifications', 'push_subscriptions', 'id'),
    ('0004_notifications', 'push_subscriptions', 'user_id'),
    ('0004_notifications', 'push_subscriptions', 'endpoint'),
    ('0004_notifications', 'push_subscriptions', 'p256dh'),
    ('0004_notifications', 'push_subscriptions', 'auth'),
    ('0004_notifications', 'push_subscriptions', 'created_at'),
    ('0004_notifications', 'analytics_events', 'id'),
    ('0004_notifications', 'analytics_events', 'user_id'),
    ('0004_notifications', 'analytics_events', 'event_type'),
    ('0004_notifications', 'analytics_events', 'entity_type'),
    ('0004_notifications', 'analytics_events', 'entity_id'),
    ('0004_notifications', 'analytics_events', 'metadata'),
    ('0004_notifications', 'analytics_events', 'created_at')
  ) AS v(migration, table_name, column_name)
),

m4_indexes AS (
  SELECT *
  FROM (VALUES
    ('0004_notifications', 'notifications_user_id_idx'),
    ('0004_notifications', 'notifications_is_read_idx'),
    ('0004_notifications', 'notifications_created_at_idx'),
    ('0004_notifications', 'notifications_user_id_is_read_created_at_idx'),
    ('0004_notifications', 'notifications_user_id_created_at_idx'),
    ('0004_notifications', 'notification_preferences_user_id_key'),
    ('0004_notifications', 'push_subscriptions_endpoint_key'),
    ('0004_notifications', 'push_subscriptions_user_id_idx'),
    ('0004_notifications', 'analytics_events_event_type_idx'),
    ('0004_notifications', 'analytics_events_user_id_idx'),
    ('0004_notifications', 'analytics_events_created_at_idx'),
    ('0004_notifications', 'analytics_events_event_type_created_at_idx')
  ) AS v(migration, index_name)
),

m4_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0004_notifications', 'notifications_user_id_fkey'),
    ('0004_notifications', 'notifications_actor_id_fkey'),
    ('0004_notifications', 'notification_preferences_user_id_fkey'),
    ('0004_notifications', 'push_subscriptions_user_id_fkey'),
    ('0004_notifications', 'analytics_events_user_id_fkey')
  ) AS v(migration, constraint_name)
),

m5_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m5_tables AS (
  SELECT *
  FROM (VALUES
    ('0005_moderation', 'table', 'phone_verification_challenges'),
    ('0005_moderation', 'table', 'user_blocks'),
    ('0005_moderation', 'table', 'content_reports')
  ) AS v(migration, kind, name)
),

m5_columns AS (
  SELECT *
  FROM (VALUES
    ('0005_moderation', 'phone_verification_challenges', 'id'),
    ('0005_moderation', 'phone_verification_challenges', 'user_id'),
    ('0005_moderation', 'phone_verification_challenges', 'phone'),
    ('0005_moderation', 'phone_verification_challenges', 'code_hash'),
    ('0005_moderation', 'phone_verification_challenges', 'attempts'),
    ('0005_moderation', 'phone_verification_challenges', 'expires_at'),
    ('0005_moderation', 'phone_verification_challenges', 'created_at'),
    ('0005_moderation', 'user_blocks', 'id'),
    ('0005_moderation', 'user_blocks', 'blocker_id'),
    ('0005_moderation', 'user_blocks', 'blocked_id'),
    ('0005_moderation', 'user_blocks', 'created_at'),
    ('0005_moderation', 'content_reports', 'id'),
    ('0005_moderation', 'content_reports', 'reporter_id'),
    ('0005_moderation', 'content_reports', 'target_type'),
    ('0005_moderation', 'content_reports', 'target_id'),
    ('0005_moderation', 'content_reports', 'reason'),
    ('0005_moderation', 'content_reports', 'details'),
    ('0005_moderation', 'content_reports', 'status'),
    ('0005_moderation', 'content_reports', 'reviewed_by_id'),
    ('0005_moderation', 'content_reports', 'reviewed_at'),
    ('0005_moderation', 'content_reports', 'resolution'),
    ('0005_moderation', 'content_reports', 'created_at')
  ) AS v(migration, table_name, column_name)
),

m5_indexes AS (
  SELECT *
  FROM (VALUES
    ('0005_moderation', 'phone_verification_challenges_user_id_idx'),
    ('0005_moderation', 'phone_verification_challenges_expires_at_idx'),
    ('0005_moderation', 'user_blocks_blocker_id_idx'),
    ('0005_moderation', 'user_blocks_blocked_id_idx'),
    ('0005_moderation', 'user_blocks_blocker_id_blocked_id_key'),
    ('0005_moderation', 'content_reports_status_created_at_idx'),
    ('0005_moderation', 'content_reports_target_type_target_id_idx'),
    ('0005_moderation', 'content_reports_reporter_id_idx')
  ) AS v(migration, index_name)
),

m5_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0005_moderation', 'phone_verification_challenges_user_id_fkey'),
    ('0005_moderation', 'user_blocks_blocker_id_fkey'),
    ('0005_moderation', 'user_blocks_blocked_id_fkey'),
    ('0005_moderation', 'content_reports_reporter_id_fkey'),
    ('0005_moderation', 'content_reports_reviewed_by_id_fkey')
  ) AS v(migration, constraint_name)
),

m6_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m6_tables AS (
  SELECT *
  FROM (VALUES
    ('0006_platform', 'table', 'background_jobs')
  ) AS v(migration, kind, name)
),

m6_columns AS (
  SELECT *
  FROM (VALUES
    ('0006_platform', 'background_jobs', 'id'),
    ('0006_platform', 'background_jobs', 'queue'),
    ('0006_platform', 'background_jobs', 'job_type'),
    ('0006_platform', 'background_jobs', 'payload'),
    ('0006_platform', 'background_jobs', 'status'),
    ('0006_platform', 'background_jobs', 'priority'),
    ('0006_platform', 'background_jobs', 'attempts'),
    ('0006_platform', 'background_jobs', 'max_attempts'),
    ('0006_platform', 'background_jobs', 'run_at'),
    ('0006_platform', 'background_jobs', 'scheduled_at'),
    ('0006_platform', 'background_jobs', 'locked_at'),
    ('0006_platform', 'background_jobs', 'completed_at'),
    ('0006_platform', 'background_jobs', 'last_error'),
    ('0006_platform', 'background_jobs', 'created_at'),
    ('0006_platform', 'background_jobs', 'updated_at')
  ) AS v(migration, table_name, column_name)
),

m6_indexes AS (
  SELECT *
  FROM (VALUES
    ('0006_platform', 'background_jobs_status_run_at_idx'),
    ('0006_platform', 'background_jobs_status_priority_run_at_idx'),
    ('0006_platform', 'background_jobs_queue_status_idx'),
    ('0006_platform', 'background_jobs_job_type_created_at_idx')
  ) AS v(migration, index_name)
),

m7_enums AS (
  SELECT *
  FROM (VALUES
  SELECT NULL WHERE false
  ) AS v(migration, kind, name)
),

m7_tables AS (
  SELECT *
  FROM (VALUES
    ('0007_security_rbac', 'table', 'roles'),
    ('0007_security_rbac', 'table', 'permissions'),
    ('0007_security_rbac', 'table', 'role_permissions'),
    ('0007_security_rbac', 'table', 'user_roles'),
    ('0007_security_rbac', 'table', 'admin_audit_logs'),
    ('0007_security_rbac', 'table', 'security_events')
  ) AS v(migration, kind, name)
),

m7_columns AS (
  SELECT *
  FROM (VALUES
    ('0007_security_rbac', 'roles', 'id'),
    ('0007_security_rbac', 'roles', 'name'),
    ('0007_security_rbac', 'roles', 'description'),
    ('0007_security_rbac', 'roles', 'is_system'),
    ('0007_security_rbac', 'roles', 'created_at'),
    ('0007_security_rbac', 'permissions', 'id'),
    ('0007_security_rbac', 'permissions', 'key'),
    ('0007_security_rbac', 'permissions', 'description'),
    ('0007_security_rbac', 'role_permissions', 'role_id'),
    ('0007_security_rbac', 'role_permissions', 'permission_id'),
    ('0007_security_rbac', 'user_roles', 'id'),
    ('0007_security_rbac', 'user_roles', 'user_id'),
    ('0007_security_rbac', 'user_roles', 'role_id'),
    ('0007_security_rbac', 'user_roles', 'granted_by_id'),
    ('0007_security_rbac', 'user_roles', 'created_at'),
    ('0007_security_rbac', 'admin_audit_logs', 'id'),
    ('0007_security_rbac', 'admin_audit_logs', 'admin_id'),
    ('0007_security_rbac', 'admin_audit_logs', 'action'),
    ('0007_security_rbac', 'admin_audit_logs', 'target_type'),
    ('0007_security_rbac', 'admin_audit_logs', 'target_id'),
    ('0007_security_rbac', 'admin_audit_logs', 'metadata'),
    ('0007_security_rbac', 'admin_audit_logs', 'ip_address'),
    ('0007_security_rbac', 'admin_audit_logs', 'created_at'),
    ('0007_security_rbac', 'security_events', 'id'),
    ('0007_security_rbac', 'security_events', 'user_id'),
    ('0007_security_rbac', 'security_events', 'event_type'),
    ('0007_security_rbac', 'security_events', 'severity'),
    ('0007_security_rbac', 'security_events', 'metadata'),
    ('0007_security_rbac', 'security_events', 'created_at')
  ) AS v(migration, table_name, column_name)
),

m7_indexes AS (
  SELECT *
  FROM (VALUES
    ('0007_security_rbac', 'roles_name_key'),
    ('0007_security_rbac', 'permissions_key_key'),
    ('0007_security_rbac', 'user_roles_user_id_idx'),
    ('0007_security_rbac', 'user_roles_role_id_idx'),
    ('0007_security_rbac', 'user_roles_user_id_role_id_key'),
    ('0007_security_rbac', 'admin_audit_logs_admin_id_idx'),
    ('0007_security_rbac', 'admin_audit_logs_action_idx'),
    ('0007_security_rbac', 'admin_audit_logs_created_at_idx'),
    ('0007_security_rbac', 'admin_audit_logs_target_type_target_id_idx'),
    ('0007_security_rbac', 'security_events_event_type_idx'),
    ('0007_security_rbac', 'security_events_severity_idx'),
    ('0007_security_rbac', 'security_events_created_at_idx'),
    ('0007_security_rbac', 'security_events_user_id_created_at_idx')
  ) AS v(migration, index_name)
),

m7_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0007_security_rbac', 'role_permissions_role_id_fkey'),
    ('0007_security_rbac', 'role_permissions_permission_id_fkey'),
    ('0007_security_rbac', 'user_roles_user_id_fkey'),
    ('0007_security_rbac', 'user_roles_role_id_fkey'),
    ('0007_security_rbac', 'user_roles_granted_by_id_fkey'),
    ('0007_security_rbac', 'admin_audit_logs_admin_id_fkey'),
    ('0007_security_rbac', 'security_events_user_id_fkey')
  ) AS v(migration, constraint_name)
),

m8_enums AS (
  SELECT *
  FROM (VALUES
    ('0008_media_platform', 'enum', 'MediaProcessingStatus')
  ) AS v(migration, kind, name)
),

m8_tables AS (
  SELECT *
  FROM (VALUES
    ('0008_media_platform', 'table', 'media_objects')
  ) AS v(migration, kind, name)
),

m8_columns AS (
  SELECT *
  FROM (VALUES
    ('0008_media_platform', 'media_objects', 'id'),
    ('0008_media_platform', 'media_objects', 'content_hash'),
    ('0008_media_platform', 'media_objects', 'storage_path'),
    ('0008_media_platform', 'media_objects', 'kind'),
    ('0008_media_platform', 'media_objects', 'mime_type'),
    ('0008_media_platform', 'media_objects', 'byte_size'),
    ('0008_media_platform', 'media_objects', 'ref_count'),
    ('0008_media_platform', 'media_objects', 'status'),
    ('0008_media_platform', 'media_objects', 'variants'),
    ('0008_media_platform', 'media_objects', 'owner_id'),
    ('0008_media_platform', 'media_objects', 'created_at'),
    ('0008_media_platform', 'media_objects', 'processed_at'),
    ('0008_media_platform', 'media_objects', 'last_error')
  ) AS v(migration, table_name, column_name)
),

m8_indexes AS (
  SELECT *
  FROM (VALUES
    ('0008_media_platform', 'media_objects_content_hash_key'),
    ('0008_media_platform', 'media_objects_owner_id_created_at_idx'),
    ('0008_media_platform', 'media_objects_status_created_at_idx'),
    ('0008_media_platform', 'media_objects_storage_path_idx')
  ) AS v(migration, index_name)
),

m8_fkeys AS (
  SELECT *
  FROM (VALUES
    ('0008_media_platform', 'media_objects_owner_id_fkey')
  ) AS v(migration, constraint_name)
),

enum_checks AS (
  SELECT
    e.migration,
    'enum'::text AS kind,
    e.name AS object_name,
    EXISTS (
      SELECT 1
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
      WHERE n.nspname = 'public'
        AND t.typname = e.name
    ) AS ok
  FROM (
    SELECT * FROM m1_enums
    UNION ALL SELECT * FROM m2_enums
  ) e
),
table_checks AS (
  SELECT
    t.migration,
    'table'::text AS kind,
    t.name AS object_name,
    EXISTS (
      SELECT 1
      FROM information_schema.tables ist
      WHERE ist.table_schema = 'public'
        AND ist.table_name = t.name
        AND ist.table_type = 'BASE TABLE'
    ) AS ok
  FROM (
    SELECT * FROM m1_tables
    UNION ALL SELECT * FROM m2_tables
    UNION ALL SELECT * FROM m3_tables
    UNION ALL SELECT * FROM m4_tables
    UNION ALL SELECT * FROM m5_tables
    UNION ALL SELECT * FROM m6_tables
    UNION ALL SELECT * FROM m7_tables
    UNION ALL SELECT * FROM m8_tables
  ) t
),
column_checks AS (
  SELECT
    c.migration,
    'column'::text AS kind,
    c.table_name || '.' || c.column_name AS object_name,
    EXISTS (
      SELECT 1
      FROM information_schema.columns ic
      WHERE ic.table_schema = 'public'
        AND ic.table_name = c.table_name
        AND ic.column_name = c.column_name
    ) AS ok
  FROM (
    SELECT * FROM m1_columns
    UNION ALL SELECT * FROM m2_columns
    UNION ALL SELECT * FROM m3_columns
    UNION ALL SELECT * FROM m4_columns
    UNION ALL SELECT * FROM m5_columns
    UNION ALL SELECT * FROM m6_columns
    UNION ALL SELECT * FROM m7_columns
    UNION ALL SELECT * FROM m8_columns
  ) c
),
index_checks AS (
  SELECT
    i.migration,
    'index'::text AS kind,
    i.index_name AS object_name,
    EXISTS (
      SELECT 1
      FROM pg_indexes pi
      WHERE pi.schemaname = 'public'
        AND pi.indexname = i.index_name
    ) AS ok
  FROM (
    SELECT * FROM m1_indexes
    UNION ALL SELECT * FROM m2_indexes
    UNION ALL SELECT * FROM m3_indexes
    UNION ALL SELECT * FROM m4_indexes
    UNION ALL SELECT * FROM m5_indexes
    UNION ALL SELECT * FROM m6_indexes
    UNION ALL SELECT * FROM m7_indexes
    UNION ALL SELECT * FROM m8_indexes
  ) i
),
fkey_checks AS (
  SELECT
    f.migration,
    'foreign_key'::text AS kind,
    f.constraint_name AS object_name,
    EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      WHERE tc.constraint_schema = 'public'
        AND tc.constraint_name = f.constraint_name
        AND tc.constraint_type = 'FOREIGN KEY'
    ) AS ok
  FROM (
    SELECT * FROM m1_fkeys
    UNION ALL SELECT * FROM m2_fkeys
    UNION ALL SELECT * FROM m3_fkeys
    UNION ALL SELECT * FROM m4_fkeys
    UNION ALL SELECT * FROM m5_fkeys
    UNION ALL SELECT * FROM m6_fkeys
    UNION ALL SELECT * FROM m7_fkeys
  ) f
),
all_checks AS (
  SELECT * FROM enum_checks WHERE migration IS NOT NULL
  UNION ALL SELECT * FROM table_checks
  UNION ALL SELECT * FROM column_checks
  UNION ALL SELECT * FROM index_checks
  UNION ALL SELECT * FROM fkey_checks
),
migration_summary AS (
  SELECT
    migration,
    COUNT(*) AS total_checks,
    COUNT(*) FILTER (WHERE ok) AS passed_checks,
    COUNT(*) FILTER (WHERE NOT ok) AS failed_checks,
    CASE WHEN bool_and(ok) THEN 'PASS' ELSE 'FAIL' END AS migration_status
  FROM all_checks
  GROUP BY migration
),
failed_details AS (
  SELECT migration, kind, object_name
  FROM all_checks
  WHERE NOT ok
  ORDER BY migration, kind, object_name
),
gate AS (
  SELECT
    CASE
      WHEN EXISTS (SELECT 1 FROM migration_summary WHERE migration_status = 'FAIL')
        THEN 'STOP — do NOT run prisma migrate resolve until all failures are investigated'
      ELSE 'GO — all migrations 0001–0008 verified; safe to proceed with migrate resolve --applied for 0001–0008, then migrate deploy for 0009_i18n'
    END AS deployment_recommendation,
    NOT EXISTS (SELECT 1 FROM migration_summary WHERE migration_status = 'FAIL') AS all_pass
  FROM migration_summary
  LIMIT 1
)

SELECT 'SUMMARY' AS section, migration, migration_status, passed_checks::text, failed_checks::text, total_checks::text
FROM migration_summary
UNION ALL
SELECT 'FAILURE', migration, kind, object_name, 'FAIL', NULL
FROM failed_details
UNION ALL
SELECT 'GATE', NULL, deployment_recommendation, CASE WHEN all_pass THEN 'PASS' ELSE 'FAIL' END, NULL, NULL
FROM gate
ORDER BY
  CASE section WHEN 'SUMMARY' THEN 1 WHEN 'FAILURE' THEN 2 WHEN 'GATE' THEN 3 END,
  migration NULLS LAST,
  migration_status NULLS LAST;
