/** Analytics event type constants. */

export const ANALYTICS_EVENTS = {
  INTRODUCTION_CREATED: "introduction_created",
  INTRODUCTION_VIEWED: "introduction_viewed",
  INTRODUCTION_SHARED: "introduction_shared",
  INTRODUCTION_REPLIED: "introduction_replied",
  INTRODUCTION_LIKED: "introduction_liked",
  INTRODUCTION_EXPIRED: "introduction_expired",
  INVITE_SENT: "invite_sent",
  INVITE_OPENED: "invite_opened",
  INVITE_ACCEPTED: "invite_accepted",
  INVITE_REGISTERED: "invite_registered",
  DISCOVERY_CREATED: "discovery_created",
  DISCOVERY_OPENED: "discovery_opened",
  DISCOVERY_EXPIRED: "discovery_expired",
  DISCOVERY_BANNER_VIEWED: "discovery_banner_viewed",
  DISCOVERY_VIEWED: "discovery_viewed",
  DISCOVERY_LIKED: "discovery_liked",
  DISCOVERY_SHARED: "discovery_shared",
  DISCOVERY_COMMENTED: "discovery_commented",
  DISCOVERY_MESSAGE_CLICKED: "discovery_message_clicked",
  MESSAGE_SENT: "message_sent",
  MESSAGE_RECEIVED: "message_received",
  CONVERSATION_STARTED: "conversation_started",
  TRUST_PROFILE_VIEWED: "trust_profile_viewed",
  SHARED_INTRODUCERS_OPENED: "shared_introducers_opened",
  TRUST_SCORE_INCREASED: "trust_score_increased",
  NEW_SHARED_INTRODUCER: "new_shared_introducer",
  PHONE_VERIFIED: "phone_verified",
  IDENTITY_VERIFIED: "identity_verified",
  APP_INSTALLED: "app_installed",
  PUSH_ENABLED: "push_enabled",
  INTRODUCTION_OPENED: "introduction_opened",
  INTRODUCTION_ACCEPTED: "introduction_accepted",
  DISCOVERY_MESSAGE_STARTED: "discovery_message_started",
  CONNECTION_CREATED: "connection_created",
  CATEGORY_JOINED: "category_joined",
  VERIFICATION_COMPLETED: "verification_completed",
  SHARED_INTRODUCER_RELATIONSHIP_CREATED: "shared_introducer_relationship_created",
} as const;

export type AnalyticsEventType = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
